'use strict';
// Fictional, ephemeral UI demonstration. No media capture, network calls or storage.
const state = {page:'home',mode:'practice',duration:30,level:'中级',topics:['并发与多线程','分布式事务'],prepFlow:false,stage:0,turn:0,recording:false,answered:false,introPending:false,updated:false,keepAudio:false,custom:false,resumeReady:false,fileName:'',role:'Java 后端工程师',jd:'',extra:'',draft:'',resumeText:'',adjust:true,ended:false};
const titles={home:'工作台',resume:'我的简历',prepare:'准备面试',room:'面试练习室',report:'复盘报告',settings:'设置',admin:'提示词管理'};
const topicData=[['并发与多线程','简历相关','订单项目涉及并发扣减，考察线程安全与锁的边界。'],['分布式事务','项目深挖','围绕订单、库存与支付之间的一致性展开。'],['JVM 与性能调优','岗位基础','考察内存模型、GC 与线上问题定位思路。'],['MySQL 与索引','简历相关','结合慢查询优化，讨论索引设计与事务隔离。'],['Redis 与缓存','岗位重点','从缓存使用递进到热点、失效与一致性。'],['AI 应用集成','拓展方向','作为假设场景讨论，不预设你有 AI 项目经验。']];
const stages=['自我介绍','技术原理','业务场景','个人与 HR'];
const questions=[['用两分钟介绍一下你自己，重点说说你负责过的项目和个人贡献。'],['在订单服务中，多个线程同时扣减库存，可能出现什么问题？','你提到用 synchronized 保护库存扣减。服务部署到多个实例后，这个方案还有效吗？','如果引入分布式锁，你会怎样处理锁过期与重复请求？','除了加锁，还有哪些方案？你会如何比较它们的吞吐量和复杂度？'],['沿用刚才的订单场景：支付已经成功，但库存服务超时，你会如何保证最终业务结果正确？','补偿消息可能重复投递，你会如何设计幂等？','补偿持续失败时，你会如何发现问题并介入处理？','业务希望尽快返回结果，你会如何平衡响应速度与一致性？'],['在这个订单项目中，哪些方案由你设计，哪些由团队共同决定？','遇到技术方案分歧时，你如何推动团队做出决定？','你希望下一份工作带来哪些变化？为什么考虑离开当前岗位？','回顾刚才的回答，你最希望补强哪项能力？']];
const sampleAnswers=['我有三年 Java 后端开发经验，主要负责电商订单模块。项目使用 Spring Boot、MySQL 和 Redis。我参与过促销活动的库存扣减改造，负责接口实现和压测，也和团队一起讨论过重复下单的处理方案。','多个线程可能同时读取到相同库存，导致超卖。我会使用 synchronized 保护读取和扣减操作，让同一时间只有一个线程执行。','我会先记录支付成功的状态，再通过消息队列重试扣减库存。失败时触发补偿，并记录日志方便排查。','我主要负责订单接口和压测。整体方案由团队一起讨论，我提出过用唯一请求号避免重复下单，但当时没有完整考虑重试失败后的处理。'];
const scores=[['专业准确性',76],['回答完整性',62],['分析与推理',71],['方案与取舍',58]];
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,cls='',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const tag=(text,cls='')=>`<span class="tag ${cls}">${text}</span>`;
const modeName=()=>state.mode==='practice'?'陪练模式':'模拟面试';
const wave=()=>`<div class="wave" aria-hidden="true">${'<i></i>'.repeat(25)}</div>`;
const heading=(kicker,title,sub,aside='')=>`<div class="heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p class="subtitle">${sub}</p></div>${aside}</div>`;
function navigate(page){state.page=page;render();window.scrollTo({top:0});}
function notify(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('visible'),3800);}
function render(){
 const nav=[['home','⌂','工作台'],['resume','▤','我的简历'],['prepare','＋','准备面试'],['report','▥','复盘报告'],['settings','⚙','设置']];
 document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="logo"><span class="logo-mark">ıı</span>ai_interviewer</div><div class="workspace"><small>个人练习空间</small><b>Java 后端 · 持续进步</b></div><nav class="nav" aria-label="主导航">${nav.map(([id,icon,label])=>btn(`<span class="navicon">${icon}</span>${label}`,`nav:${id}`,state.page===id?'active':'')).join('')}</nav><div class="notice">把每一次回答，<br>变成下一次的底气。</div><div class="sidebar-foot"><div class="avatar">林</div><div><b>林同学</b><br><small>演示账号</small></div></div></aside><main class="main"><header class="topbar"><span class="breadcrumb">个人空间 <span class="muted"> / </span> <strong>${titles[state.page]}</strong></span><span class="row">${tag('● 所有内容均为演示','blue')}<span class="avatar">林</span></span></header><div class="content">${({home:homePage,resume:resumePage,prepare:preparePage,room:roomPage,report:reportPage,settings:settingsPage,admin:adminPage}[state.page])()}</div><nav class="mobile-nav" aria-label="小程序导航">${[['home','⌂','首页'],['resume','▤','简历'],['prepare','＋','面试'],['report','▥','复盘'],['settings','⚙','设置']].map(([id,icon,label])=>btn(`<span>${icon}</span>${label}`,`nav:${id}`,state.page===id?'active':'')).join('')}</nav></main></div>`;
}
function homePage(){return `${heading('YOUR NEXT STEP','今天，练好一个回答。','从真实经历出发，练出清晰、有深度的表达。',tag('Java 后端练习空间'))}<section class="card hero"><div><div class="eyebrow">有准备地面对下一场面试</div><h1>让技术说得清楚，<br>让经历更有说服力。</h1><p>结合你的简历与目标岗位，从技术原理到业务取舍，完成一场有脉络的面试。</p><div class="row">${btn('开始新的面试 →','nav:resume','primary')}${btn('直接体验面试室','demo-room')}</div></div><div class="hero-art" aria-hidden="true">${'<i></i>'.repeat(11)}</div></section><div class="grid3 section-title"><div class="card"><span class="muted">已完成练习</span><div class="metric">06<span>场 · 示例</span></div><small>每一次练习，都留下成长记录</small></div><div class="card"><span class="muted">累计练习</span><div class="metric">148<span>分钟 · 示例</span></div><small>专注于表达与思考的时间</small></div><div class="card"><span class="muted">最近训练重点</span><div class="metric" style="font:21px 'Microsoft YaHei',sans-serif">方案取舍</div><small>下一次，试着比较两个备选方案</small></div></div><div class="grid2"><section class="card"><div class="row between"><h2>最近的练习</h2>${tag('示例记录')}</div><div class="list-row"><div><b>订单一致性与并发控制</b><p>陪练模式 · 中级 · 30 分钟</p></div>${btn('查看复盘 ↗','nav:report')}</div><div class="list-row"><div><b>缓存设计与性能优化</b><p>模拟面试 · 中级 · 45 分钟</p></div>${tag('示例 · 仅展示')}</div></section><section class="card"><h2>一场有脉络的面试</h2>${[['01','读懂你的经历','从简历里找到值得深入的项目。'],['02','一起确定重点','选择技术方向，补充你的练习目标。'],['03','逐层深入，再复盘','从“是什么”走向“为什么这样做”。']].map(([n,t,d])=>`<div class="list-row"><div class="row"><span class="step-number">${n}</span><div><b>${t}</b><p>${d}</p></div></div></div>`).join('')}</section></div>`;}
function resumePage(){return `${heading('01 / UNDERSTAND YOUR EXPERIENCE','先认识你的经历','导入简历，确认信息后再生成适合你的面试方向。')}<div class="grid2"><section class="card"><h2>导入简历</h2><div class="dropzone"><div class="upload-icon">↥</div><h3>${state.fileName?esc(state.fileName):'选择一份简历'}</h3><p>PDF、DOCX、Markdown、TXT<br>原型仅演示选择，不读取或上传文件</p><input id="resume-file" type="file" accept=".pdf,.docx,.md,.txt" class="hidden"><label for="resume-file" class="screen-reader">选择简历文件</label>${btn('选择文件','choose-file')}</div><p class="muted" style="text-align:center;margin:18px 0;font-size:12px">或者，直接粘贴简历内容</p><label class="field">简历文本<textarea data-field="resumeText" placeholder="粘贴你的项目经历、技术栈与工作经历…">${esc(state.resumeText)}</textarea></label><div class="notice">本版使用虚构简历展示分析结果。你的文件与输入不会发送给模型。</div><div class="actions">${btn('载入示例分析 →','analyze','primary')}</div></section><section class="card"><div class="row between"><h2>确认分析结果</h2>${tag(state.resumeReady?'待你确认':'虚构示例','blue')}</div><label class="field">候选人概况<input type="text" value="${esc(state.candidate || '林同学 · Java 后端 · 3 年经验')}" aria-label="候选人概况" data-field="candidate"></label><div class="row">${['Java','Spring Boot','MySQL','Redis','消息队列'].map(x=>tag(x)).join('')}</div><div class="resume-block"><h3>电商订单与库存服务</h3><p>负责订单接口与促销库存扣减改造，参与压测及重复下单处理方案讨论。</p></div><div class="resume-block"><h3>值得深入的线索</h3><p>并发库存扣减 · 多实例部署 · 重复请求<br>可以进一步明确个人贡献与效果指标。</p></div><label class="field" style="margin-top:20px">修正或补充项目内容<textarea data-field="resumeCorrection" placeholder="例如：库存方案由团队设计，我主要负责接口实现与压测。">${esc(state.resumeCorrection || '')}</textarea></label><div class="actions">${btn('确认示例，准备面试 →','confirm-resume','primary')}</div></section></div>`;}
function preparePage(){if(state.prepFlow)return flowPage();return `${heading('02 / BUILD YOUR INTERVIEW','这一次，你想重点练什么？','一起确定目标，让每一个问题都有来由。')}${sessionStylePanel()}<div class="conversation"><div class="message"><span class="bot">ai</span><section class="bubble"><h3>已经了解你的订单项目经历。</h3><p>先告诉我这次的目标岗位。如果有招聘描述，我可以进一步对齐考察重点。</p><div class="fields"><label class="field">目标岗位<input data-field="role" type="text" value="${esc(state.role)}"></label><label class="field">目标级别<select data-field="level">${['初级','中级','高级'].map(x=>`<option ${state.level===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label class="field">岗位描述 JD <span class="muted">· 可选</span><textarea data-field="jd" placeholder="粘贴招聘要求；没有 JD 也可以继续。">${esc(state.jd)}</textarea></label></section></div><div class="message"><span class="bot">ai</span><section class="bubble"><div class="row between"><h3>这些方向，值得一起深入。</h3>${tag('可多选','blue')}</div><p>下方为基于示例简历的推荐。真实产品会结合简历与岗位动态生成。</p><div class="topic-grid">${topicData.map(([name,source,desc])=>`<label class="topic"><input type="checkbox" data-topic="${name}" ${state.topics.includes(name)?'checked':''}><span><b>${name}</b><small>${source} · ${desc}</small></span></label>`).join('')}</div><label class="field" style="margin-top:18px">还有什么想补充？<textarea data-field="extra" placeholder="例如：少问概念，多围绕订单项目追问；重点训练方案取舍。">${esc(state.extra)}</textarea></label></section></div><div class="message"><span class="bot">ai</span><section class="bubble"><h3>选择本次练习方式</h3><div class="choice">${btn('陪练模式<small>每轮评分与建议，边练边改。</small>','mode:practice','',`aria-pressed="${state.mode==='practice'}"`)}${btn('模拟面试<small>过程中不提示，结束后统一复盘。</small>','mode:mock','',`aria-pressed="${state.mode==='mock'}"`)}</div><h3 style="margin-top:22px">计划时长</h3><div class="choice">${[[15,'专项'],[30,'标准'],[45,'深度']].map(([m,t])=>btn(`${m} 分钟<small>${t}练习</small>`,`duration:${m}`,'',`aria-pressed="${state.duration===m}"`)).join('')}</div><label class="row" style="margin-top:20px;font-size:12px"><input type="checkbox" data-field="keepAudio" ${state.keepAudio?'checked':''}>保留本场录音，方便回听</label><small>默认仅保存转写与评价。此原型不进行录音或持久保存。</small><div class="actions">${btn('查看面试流程 →','generate','primary')}</div></section></div></div>`;}
function flowPage(){return `${heading('03 / YOUR INTERVIEW PLAN','每一步，都为下一步做准备。','先了解考察路径，具体问题会随你的回答逐步展开。',btn('← 调整偏好','edit-prep'))}<div class="card"><div class="row between"><div><h2>${esc(state.role)} · ${esc(state.level)}</h2><div class="row">${tag(modeName(),'blue')}${tag(state.duration+' 分钟')}${tag(state.keepAudio?'已选择保留录音':'不保留录音')}</div></div>${tag('示例大纲','green')}</div><div class="flow">${stages.map((x,i)=>`<div class="flow-node"><span class="step-number">0${i+1}</span><b>${x}</b><p>${['经历与职责<br>根据介绍更新后续大纲','基础 → 原理 → 边界<br>沿选定技术方向深入','场景 → 方案 → 取舍<br>回到真实项目约束','贡献 → 协作 → 动机<br>讲清自己的选择'][i]}</p></div>`).join('')}</div><div class="grid2"><div><h3>本场考察方向</h3><div class="row">${state.topics.map(x=>`<span class="summary-chip">${esc(x)}</span>`).join('')}</div><p class="subtitle" style="margin-top:15px">典型递进：技术基础 → 多实例边界 → 业务一致性 → 个人贡献</p></div><div class="notice">${state.mode==='practice'?'每次回答后展示反馈。自我介绍带来新的考察线索时，会先请你确认大纲调整。':'本场不展示即时评分或提示。自我介绍结束后，将自动更新后续大纲；完成后统一复盘。'}<br>原型中的题目和评分固定，用于验证操作流程。</div></div><div class="actions">${btn('开始自我介绍 →','start','primary')}</div></div>`;}
function outline(){return `<h3>本场流程</h3>${stages.map((name,i)=>`<div class="stage ${i===state.stage?'active':i<state.stage?'done':''}"><span class="step-number">${i<state.stage?'✓':i+1}</span><div><b>${name}</b><small>${i<state.stage?'已完成':i===state.stage?'进行中':'待开始'}</small></div></div>`).join('')}<div class="room-meta">${state.duration} 分钟 · ${esc(state.level)}<br>${state.topics.map(esc).join(' / ')}${state.updated?'<br><span style="color:var(--blue)">↳ 已加入重复请求与幂等线索</span>':''}</div>`;}
function roomPage(){const question=state.stage===2&&state.turn===1&&!state.updated?'你会如何设定重试次数和间隔，避免故障期间放大系统压力？':questions[state.stage][state.turn];return `${heading('INTERVIEW ROOM',stages[state.stage],`按自己的节奏思考，再开始回答。`,tag(modeName(),'blue'))}<details class="mobile-flow"><summary>第 ${state.stage+1} / 4 环节 · 查看面试流程</summary>${outline()}</details><div class="room"><aside class="card outline">${outline()}</aside><section class="card"><div class="row between">${tag(state.turn===0?'主问题':`追问 ${state.turn} / 3`,'blue')}<small>示例问题 · 语音交互演示</small></div><div class="row" style="margin-top:22px"><span class="bot">ai</span><div><b>面试官</b><br><small>${state.stage===0?'先从你的经历开始':'沿着你的回答，继续深入'}</small></div></div><h2 class="question">${question}</h2><div class="question-context">${state.stage===0?'介绍结束后，将结合你补充的信息更新后续考察方向。':`承接线索：${state.stage===1?'订单库存扣减 → 并发边界':state.stage===2?'并发控制 → 跨服务一致性':'业务方案 → 个人贡献'}`}</div><div class="answer"><div class="row between"><b style="font-size:12px">你的回答</b>${tag(state.recording?'演示转写中':state.answered?'本轮已提交':'等待开始',state.recording?'blue':'')}</div>${state.recording?`<textarea aria-label="演示回答文本" data-field="draft">${esc(state.draft)}</textarea><small>可编辑示例文字；未使用麦克风。</small>`:state.answered?`<p>${esc(state.draft)}</p>`:'<p class="muted">点击下方按钮，体验一轮回答。原型将载入示例转写。</p>'}</div>${state.introPending?`<div class="update"><h3>从自我介绍中发现新线索</h3><p>你提到参与过重复下单处理，建议将“幂等设计”加入后续订单场景。</p><label><input type="checkbox" data-field="adjust" ${state.adjust?'checked':''}>补充重复请求与幂等追问</label>${btn('确认大纲调整','confirm-update','primary')}</div>`:''}<div class="voice ${state.recording?'recording':''}">${wave()}${!state.answered?btn(state.recording?'■ 回答完成':'● 开始回答（演示）',state.recording?'finish-answer':'record','primary'):state.introPending?'<small>确认上方调整后，即可进入下一环节。</small>':btn(state.stage===0?'开始技术环节 →':state.turn<3?'开始追问 →':state.stage<3?'开始下一环节 →':'完成面试，查看报告 →','next','primary')}<p>${state.recording?'演示状态 · 没有真实录音':state.answered?'本轮回答已完成，由你决定何时继续':'手动开始 · 手动提交 · 留出思考时间'}</p></div><div class="actions">${state.answered&&state.mode==='practice'?btn('重新回答','retry','ghost'):''}${state.stage>0?btn('结束当前问题 / 环节','end-stage','ghost'):''}${btn('结束本场','end-session','ghost danger')}</div></section><aside class="card feedback">${feedback()}</aside></div>`;}
function feedback(){if(state.mode==='mock')return `<h3>专注于当前回答</h3><div class="empty"><div class="empty-icon">◎</div>模拟面试进行中<br>本场结束后统一展示评价</div><div class="feedback-block"><h3>本场信息</h3><p>${esc(state.role)} · ${esc(state.level)}<br>计划 ${state.duration} 分钟<br>${state.keepAudio?'已选择保留录音':'仅保存转写与评价'}</p><small>原型不会实际保存上述数据。</small></div>`;if(!state.answered)return `<div class="row between"><h3>本轮反馈</h3>${tag('陪练','blue')}</div><div class="empty"><div class="empty-icon">◌</div>回答结束后，<br>在这里查看评分与优化建议。</div><div class="notice">先完整表达自己的思路，再根据反馈尝试改进。</div>`;return `<div class="row between"><h3>本轮反馈</h3>${tag('固定示例','amber')}</div><div class="score">${state.stage===0?'74':'68'}<small> / 100</small></div><p class="subtitle">${state.stage===0?'经历清楚，个人贡献还可以更具体。':'方向正确，但边界条件还没讲完整。'}</p>${scores.map(([x,n])=>`<div class="score-row"><span>${x}</span><span class="bar"><i style="width:${n}%"></i></span><span>${n}</span></div>`).join('')}<div class="feedback-block"><h3>做得好的地方</h3><p>${state.stage===0?'介绍了技术栈和具体项目，并说明参与的工作。':'先识别了问题，再给出解决思路，表达有基本结构。'}</p></div><div class="feedback-block"><h3>还缺少什么</h3><p>${state.stage===0?'“参与改造”没有明确你的决策范围，也缺少可核实的效果。':'方案适用的前提、失败路径和替代方案不够明确。'}</p><div class="quote">示例分析依据为预置回答，不随编辑文字重新评分。</div></div><div class="feedback-block"><h3>下一次这样改</h3><p>${state.stage===0?'按“背景 → 我的职责 → 具体行动 → 结果”组织，补充真实指标，不编造数据。':'先说明约束与假设，再解释方案；最后补充失败处理与一种替代方案。'}</p></div>`;}
function reportPage(){return `${heading('REFLECT / IMPROVE / REPEAT','把这次经历，变成下次的进步。','以下为预置示例报告，不是对本次输入的真实评价。',tag('示例报告','amber'))}<section class="card"><div class="report-top"><div class="big-score"><strong>72</strong><small>示例综合表现 / 100</small></div><div><h2>基础表达清楚，方案取舍需要更深入。</h2><p class="muted">你能说明常见技术的用途。面对复杂场景时，可以进一步补充适用前提、失败处理和验证结果。</p><div class="row">${tag(esc(state.role))}${tag(esc(state.level))}${tag(modeName(),'blue')}${tag('未验证实际编码能力')}</div></div></div><div class="dimension-grid" style="margin-top:25px">${[['专业准确性',78],['切题与完整性',72],['分析与推理',70],['方案与取舍',58],['项目深度与贡献',68],['证据与一致性',74],['表达与结构',82],['沟通与反思',74]].map(([n,s])=>`<div class="score-row"><span style="min-width:100px">${n}</span><span class="bar"><i style="width:${s}%"></i></span><b>${s}</b></div>`).join('')}</div><div class="notice">评分维度与权重仍待评审。实际报告应区分首次回答、辅导后回答及未考察项，并引用回答证据。</div></section><div class="grid2 section-title"><section class="card"><h2>沿着问题，回看思考过程</h2><div class="review-path"><span>并发基础</span>→<span>多实例边界</span>→<span>业务一致性</span>→<span>个人贡献</span></div><details open><summary>01 · 本地锁能解决多实例并发吗？</summary><p><b>示例回答：</b>“我会使用 synchronized 保护读取和扣减操作。”</p><p><b>问题：</b>没有说明本地锁的作用范围，不能覆盖多实例部署。</p><p><b>优化：</b>先明确部署边界，再比较数据库条件更新与其他并发控制方案。</p></details><details><summary>02 · 补偿失败后，如何保证业务闭环？</summary><p>补充幂等、重试上限、异常告警、人工处理与对账机制，并解释各自职责。</p></details></section><section class="card"><h2>下一次，专注这三件事</h2>${[['01','先讲约束，再讲方案','明确并发量、部署方式和一致性要求。'],['02','给出比较，而非罗列术语','至少比较两个方案，解释选择依据。'],['03','让个人贡献可被理解','说清你做了什么，以及如何验证结果。']].map(([n,t,d])=>`<div class="list-row"><div class="row"><span class="step-number">${n}</span><div><b>${t}</b><p>${d}</p></div></div></div>`).join('')}<div class="actions">${btn('带着这些重点再练一次 →','practice-again','primary')}</div><small>录音回听区域将在真实录音能力接入后验证。</small></section></div>`;}
function settingsPage(){return `${heading('YOUR PREFERENCES','让面试按你的方式进行','默认即可开始；有需要时，再调整模型与数据偏好。')}${stylePanel()}<div class="grid2"><section class="card"><h2>模型配置</h2><div class="choice">${btn('平台默认<small>无需填写密钥</small>','api:default','',`aria-pressed="${!state.custom}"`)}${btn('自定义 API<small>使用自己的服务配置</small>','api:custom','',`aria-pressed="${state.custom}"`)}</div>${state.custom?`<div class="notice amber" style="margin:18px 0">仅演示表单，请勿输入真实密钥。此页面不会保存或验证配置。</div><label class="field">厂商<select><option>GLM</option><option>DeepSeek</option><option>Qwen</option></select></label><label class="field">API 地址<input type="text" placeholder="填写厂商地址或兼容服务地址"></label><label class="field">模型名称<input type="text" placeholder="填写模型标识"></label><label class="field">API Key<input type="password" autocomplete="off" placeholder="请勿输入真实密钥 · 原型占位"></label><div class="actions">${btn('连接测试（演示）','connection')}</div>`:`<div class="setting-row"><div><b>面试规划、追问与评价</b><p>由平台提供默认模型</p></div>${tag('选型待定')}</div><div class="setting-row"><div><b>语音识别与播报</b><p>与文本模型分别配置</p></div>${tag('选型待定')}</div><div class="notice" style="margin-top:20px">GLM、DeepSeek、Qwen 的具体模型和语音能力将在技术选型阶段核实。</div>`}</section><section class="card"><h2>账号与数据</h2><div class="setting-row"><div><b>林同学 · 演示账号</b><p>Web 与小程序使用同一份练习记录</p></div>${tag('示例')}</div><div class="setting-row"><div><b>转写与评价</b><p>默认保留，用于面试复盘</p></div>${tag('默认保存','green')}</div><div class="setting-row"><div><b>回答录音</b><p>每场开始前，由你选择是否保留</p></div>${tag('自主选择')}</div><div class="notice" style="margin-top:20px">本原型所有状态仅存在于当前页面，刷新即重置。真实数据保存期限与删除流程尚待确认。</div></section></div>`;}
document.addEventListener('input',event=>{const el=event.target;if(el.dataset.field)state[el.dataset.field]=el.type==='checkbox'?el.checked:el.value;});
document.addEventListener('change',event=>{const el=event.target;if(el.dataset.topic){state.topics=el.checked?[...new Set([...state.topics,el.dataset.topic])]:state.topics.filter(x=>x!==el.dataset.topic);}if(el.id==='resume-file'){state.fileName=el.files[0]?.name||'';render();notify('仅记录文件名；未读取或上传文件。');}});
document.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target)return;const [action,value]=target.dataset.action.split(':');if(handlePromptAction(action,value))return;switch(action){
 case'nav':if(value==='prepare'&&state.page==='settings')sessionStyle={...defaultStyle};navigate(value);return;
 case'choose-file':document.querySelector('#resume-file').click();return;
 case'analyze':state.resumeReady=true;notify('已载入虚构简历分析结果，未分析你的文件。');break;
 case'confirm-resume':sessionStyle={...defaultStyle};state.resumeReady=true;state.prepFlow=false;navigate('prepare');return;
 case'mode':state.mode=value;break;
 case'duration':state.duration=Number(value);break;
 case'generate':if(!state.topics.length){notify('请至少选择一个考察方向。');return;}if(!state.role.trim()){notify('请填写目标岗位。');return;}state.prepFlow=true;window.scrollTo({top:0});break;
 case'edit-prep':state.prepFlow=false;break;
 case'start':lockConfiguration();state.stage=0;state.turn=0;state.answered=false;state.recording=false;state.updated=false;state.introPending=false;state.ended=false;navigate('room');return;
 case'demo-room':state.stage=1;state.turn=0;state.draft=sampleAnswers[1];state.answered=true;state.recording=false;state.introPending=false;navigate('room');return;
 case'record':state.recording=true;state.draft=sampleAnswers[state.stage];break;
 case'finish-answer':if(!state.draft.trim()){notify('请保留或填写一段演示回答再提交。');return;}state.recording=false;state.answered=true;if(state.stage===0&&!state.updated){if(state.mode==='practice')state.introPending=true;else{state.updated=true;notify('已自动加入重复请求与幂等线索（演示）。');}}break;
 case'confirm-update':state.updated=state.adjust;state.introPending=false;notify(state.adjust?'已将幂等线索加入后续大纲。':'保留原大纲。');break;
 case'retry':state.answered=false;state.recording=false;state.introPending=false;notify('开始新一轮演示回答；此原型不保存重答历史。');break;
 case'next':if(state.stage===0){state.stage=1;state.turn=0;}else if(state.turn<3){state.turn++;}else if(state.stage<3){state.stage++;state.turn=0;}else{state.ended=true;navigate('report');return;}state.answered=false;state.recording=false;state.draft='';break;
 case'end-stage':if(state.stage<3){state.stage++;state.turn=0;state.answered=false;state.recording=false;state.draft='';notify('已结束当前环节，未完成内容在正式版中将标记为未考察。');}else{state.ended=true;navigate('report');return;}break;
 case'end-session':if(!window.confirm('结束本场演示并查看预置报告？未完成内容不会产生真实评分。'))return;state.recording=false;state.ended=true;navigate('report');return;
 case'practice-again':state.mode='practice';state.extra='重点训练方案取舍：说明约束，比较备选方案，补充验证依据。';state.prepFlow=false;navigate('prepare');return;
 case'api':state.custom=value==='custom';break;
 case'connection':notify('这里只展示连接测试入口；未发送任何请求。');return;
}render();});
document.querySelector('#desktop').addEventListener('click',()=>setDevice(false));
document.querySelector('#mobile').addEventListener('click',()=>setDevice(true));
function setDevice(mobile){document.querySelector('#viewport').classList.toggle('mobile',mobile);document.querySelector('#mobile').classList.toggle('selected',mobile);document.querySelector('#desktop').classList.toggle('selected',!mobile);}
render();
